#!/bin/sh

# Bump the patch version in package.json
npm version patch --no-git-tag-version
git add package.json

# Run type coverage check
mkdir -p .github
npx type-coverage --json-output > .github/type-coverage.json

# Add type coverage output to the commit
git add .github/type-coverage.json

# Run linting check but don't fail the commit
echo "Running lint check... 🕵🏼‍♀️"
npm run lint || echo "Linting reported issues, but continuing with commit"
echo "Lint check done ✅"